import fs from "fs";
import path from "path";

const MD_FILES: Array<{ name: string; file: string }> = [
  { name: "DOC_OVERVIEW", file: "md/ai/context/overview.md" },
  { name: "DOC_CONCEPTS", file: "md/ai/context/concepts.md" },
  { name: "DOC_CLI", file: "md/ai/context/cliExamples.md" },
  { name: "DOC_API", file: "md/ai/context/apiExamples.md" },
  { name: "DOC_CONFIG", file: "md/ai/context/config.md" },
];

const escapeForTemplateLiteral = (content: string): string =>
  content.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");

if (import.meta.main) {
  console.log("Generating MCP docs...");

  const repoRoot = path.resolve(__dirname, "../../../");
  const outDir = path.resolve(__dirname, "../src/internal/generated/aiDocs");

  fs.mkdirSync(outDir, { recursive: true });

  const constants = MD_FILES.map(({ name, file }) => {
    const filePath = path.join(repoRoot, file);
    console.log(`Reading ${path.relative(repoRoot, filePath)}`);
    const content = fs.readFileSync(filePath, "utf8").trimEnd();
    return `export const ${name} = \`${escapeForTemplateLiteral(content)}\`;`;
  });

  const output = [
    "// This file is generated by scripts/generateMcpDocs.ts. Do not edit manually.",
    "",
    ...constants,
    "",
  ].join("\n");

  const outPath = path.join(outDir, "docs.ts");
  fs.writeFileSync(outPath, output);
  console.log(`Written to ${path.relative(repoRoot, outPath)}`);

  console.log("Finished MCP docs generation");
}
