import fs from "fs";
import path from "path";
import {
  generateAgentDocs,
  type AgentDocFileName,
} from "bw-meta/util/agentDocs";

const VAR_NAMES: Record<AgentDocFileName, string> = {
  overview: "DOC_OVERVIEW",
  concepts: "DOC_CONCEPTS",
  cliExamples: "DOC_CLI",
  apiExamples: "DOC_API",
  config: "DOC_CONFIG",
  development: "DOC_DEVELOPMENT",
};

const escapeForTemplateLiteral = (content: string): string =>
  content.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");

if (import.meta.main) {
  const { logger, contents, combinedContent } = await generateAgentDocs({
    scriptName: "bw: Public Agent Docs",
  });

  const constants = Object.entries(contents).map(([name, content]) => {
    return `export const ${VAR_NAMES[name as AgentDocFileName]} = \`${escapeForTemplateLiteral(content)}\`;`;
  });

  const moduleOutDir = path.resolve(
    __dirname,
    "../src/internal/generated/aiDocs",
  );

  fs.mkdirSync(moduleOutDir, { recursive: true });

  const moduleContent = [
    "// This file is generated by scripts/generatePublicAgentDocs.ts. Do not edit manually.",
    "",
    ...constants,
    "",
  ].join("\n");

  const modulePath = path.join(moduleOutDir, "docs.ts");
  logger.info(`Writing ${path.relative(process.cwd(), modulePath)}...`);
  fs.writeFileSync(modulePath, moduleContent);

  const agentsMdPath = path.join(process.cwd(), "AGENTS.md");
  logger.info(`Writing ${path.relative(process.cwd(), agentsMdPath)}...`);
  fs.writeFileSync(agentsMdPath, combinedContent);

  logger.info("Success");
}
