import fs from "fs";
import path from "path";
import { createScriptLogger } from "bw-meta/util";

const MD_FILES: Array<{ name: string; file: string }> = [
  { name: "DOC_OVERVIEW", file: "md/ai/context/overview.md" },
  { name: "DOC_CONCEPTS", file: "md/ai/context/concepts.md" },
  { name: "DOC_CLI", file: "md/ai/context/cliExamples.md" },
  { name: "DOC_API", file: "md/ai/context/apiExamples.md" },
  { name: "DOC_CONFIG", file: "md/ai/context/config.md" },
];

const escapeForTemplateLiteral = (content: string): string =>
  content.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");

const root = process.env.BW_PROJECT_PATH as string;

const logger = createScriptLogger({ name: "MCP Docs" });

if (import.meta.main) {
  logger.info("Generating MCP docs...");

  const outDir = path.resolve(__dirname, "../src/internal/generated/aiDocs");

  fs.mkdirSync(outDir, { recursive: true });

  const constants = MD_FILES.map(({ name, file }) => {
    const filePath = path.join(root, file);
    logger.info(`Reading ${path.relative(root, filePath)}`);
    const content = fs.readFileSync(filePath, "utf8").trimEnd();
    return `export const ${name} = \`${escapeForTemplateLiteral(content)}\`;`;
  });

  const output = [
    "// This file is generated by scripts/generateMcpDocs.ts. Do not edit manually.",
    "",
    ...constants,
    "",
  ].join("\n");

  const outPath = path.join(outDir, "docs.ts");

  logger.debug(`Writing ${outPath}...`);

  fs.writeFileSync(outPath, output);
  logger.info(`Written to ${path.relative(root, outPath)}`);

  logger.info("Finished MCP docs generation");
}
